NATS:
  host: nats.cloud.gcm
  port: 4222
  cache_ttl: 3600
  subscription: object.sensor-info-request
SensorInformationDataBase:
  zabbix_use_tls: true # Использовать TLS для подключения к Zabbix
  zabbix_host: 192.168.9.45
  zabbix_port: 443
  zabbix_user: 803.a.belyakov@avz-center.ru
  netbox_host: netbox.cloud.gcm
  netbox_port: 8005
  ncircc_url: https://10.0.227.10/api/v2/companies
  request_timeout: 15
WriteLogDataBase:
  host: datahook.cloud.gcm
  port: 9200
  user: log_writer
  namedb:
  storage_name_db: enricher_geoip
DebugServer:
  enable: false
  host: localhost
  port: 6262
