NATS:
  host: nats.cloud.gcm
  port: 4222
  cache_ttl: 3600
  subscription: object.geoip-request
GeoIPDataBase:
  host: pg2.cloud.gcm
  port: 88
  path: ip
  request_timeout: 7
WriteLogDataBase:
  host: datahook.cloud.gcm
  port: 9200
  user: log_writer
  namedb:
  storage_name_db: enricher_geoip
